### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by JWLEESF** [ednunezg/pytrendline#6]
Traceback (most recent call last):
  File "C:\Users\X\Desktop\PERSONAL\Python\pytrendline-master\example.py", line 29, in <module>
    results = pytrendline.detect(
  File "C:\Users\X\Desktop\PERSONAL\Python\pytrendline-master\pytrendline\detect.py", line 385, in detect
    support_trendlines, support_pivots = detect_wrapped(structs.TrendlineTypes.SUPPORT)
  File "C:\Users\X\Desktop\PERSONAL\Python\pytrendline-master\pytrendline\detect.py", line 347, in detect_wrapped
    trends_df = trends_df.append({
  File "C:\Users\X\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

How can I fix this?

**Comment by wkarny** [comment]
Fixed by PR #7
